/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraphique;


import Capteurs.Poids.CapteurPoids;
import Capteurs.Temperature.CapteurTemperature;
import Controleurs.ControleurCapteurs;
import Ruche.Cadre;
import Controleurs.ControleurPoids;
import Controleurs.ControleurInterface;
import Ruche.Couvercle;
import Ruche.Hausse;
import Ruche.Materiau;
import Ruche.Materiel;
import Ruche.Plancher;
import Ruche.Ruche;
import Ruche.Toit;
import SQL.Affichage;
import SQL.BDTable;
import SQL.Création;
import SQL.Destruction;
import SQL.Modification;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import static java.lang.Thread.sleep;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import static java.sql.Connection.TRANSACTION_READ_COMMITTED;
import java.sql.SQLException;

/**
 *
 * @author matterv
 */
public class AppClient extends javax.swing.JFrame {
    private Affichage affichage;
    private String currentRucheId;
    private String currentHausseId;
    private String currentCadreId;
    private String currentStockId;
    private ControleurInterface contI;
    private ControleurCapteurs contC;

    /**
     * Creates new form AppClient
     */
    public AppClient() {
        affichage = new Affichage();
        contI = new ControleurInterface();
        contC = new ControleurCapteurs();
        initComponents();
        this.panelDeuxième.setVisible(false);

    }

    private void refresh(){
        String[] textToSet = contI.afficheSQLRuche(currentRucheId);
        jLabel16.setText(textToSet[0]);
        jLabel17.setText(textToSet[1]);
        jLabel18.setText(textToSet[2]);
        textCaptPoidsAssocier.setText(textToSet[3]);

        //new javax.swing.DefaultComboBoxModel(affichage.SQLRuche("idRuche").split(" ")));

//        displayRuches.addItemListener(new java.awt.event.ItemListener() {
//            public void itemStateChanged(java.awt.event.ItemEvent evt) {
//                displayRuchesItemStateChanged(evt);
//            }
//        });
//        displayRuches.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                displayRuchesActionPerformed(evt);
//            }
//        });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        undoBouton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        associerRucheBouton = new javax.swing.JButton();
        supprimerRuche = new javax.swing.JButton();
        displayRuches = new javax.swing.JComboBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jSeparator1 = new javax.swing.JSeparator();
        associerHausseBouton = new javax.swing.JButton();
        displayHausse = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        nomRucheAffichage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        textHausseCouleur = new javax.swing.JLabel();
        textHausseNumero = new javax.swing.JLabel();
        textHausseMateriau = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        textTemperature = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        capteurAssociéText = new javax.swing.JLabel();
        capteurTemperatureAssocieCombo = new javax.swing.JComboBox<>();
        associerCapteurTemperatureBouton = new javax.swing.JButton();
        dissocierCapteurTemperatureBouton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        textCouleurAfficher = new javax.swing.JLabel();
        textRaceAfficher = new javax.swing.JLabel();
        textAgeAfficher = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        actionEnregistrerBouton = new javax.swing.JButton();
        typeIntervention = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        detailsText = new javax.swing.JLabel();
        detailCombo = new javax.swing.JComboBox<>();
        panelDeuxième = new javax.swing.JPanel();
        deuxièmeText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        detailsText1 = new javax.swing.JLabel();
        detailCombo1 = new javax.swing.JComboBox<>();
        interventionDeux = new javax.swing.JLabel();
        deuxiemeIntervention = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ajouterCadresBouton = new javax.swing.JButton();
        displayCadre = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        matiereCadre = new javax.swing.JLabel();
        EtatCadre = new javax.swing.JLabel();
        contenuCadre = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        poidsCadre = new javax.swing.JLabel();
        capteurPoisdAssociéBox = new javax.swing.JComboBox<>();
        textCaptPoidsAssocier = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        associerCapteurPoidsBouton = new javax.swing.JButton();
        dissocierCapteurPoidsBouton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        typeMaterielCombo = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        typeMateriauCombo = new javax.swing.JComboBox<Materiau>();
        ajoutMateriauBouton = new javax.swing.JToggleButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        stockCombo = new javax.swing.JComboBox<>();
        ButtonSupprimerMateriel = new javax.swing.JToggleButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Open Sans Extrabold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Abeillix2000");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);

        undoBouton.setText("Undo");
        undoBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undoBoutonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undoBouton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(undoBouton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        associerRucheBouton.setBackground(new java.awt.Color(255, 255, 153));
        associerRucheBouton.setText("Associer Ruche");
        associerRucheBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                associerRucheBoutonMouseClicked(evt);
            }
        });
        associerRucheBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associerRucheBoutonActionPerformed(evt);
            }
        });

        supprimerRuche.setBackground(new java.awt.Color(255, 255, 153));
        supprimerRuche.setText("Dissocier Ruche");
        supprimerRuche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerRucheMouseClicked(evt);
            }
        });

        String[] listRuches = affichage.SQLRuche("idRuche").split(" ");
        if (listRuches.length != 0 ){
            currentRucheId = listRuches[0];
        }
        displayRuches.setModel(new javax.swing.DefaultComboBoxModel(listRuches));
        displayRuches.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                displayRuchesItemStateChanged(evt);
            }
        });
        displayRuches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayRuchesActionPerformed(evt);
            }
        });

        associerHausseBouton.setBackground(new java.awt.Color(255, 255, 153));
        associerHausseBouton.setText("Associer Hausse");
        associerHausseBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                associerHausseBoutonMouseClicked(evt);
            }
        });

        String[] listH = {};
        displayHausse.setModel(new javax.swing.DefaultComboBoxModel(listH));
        int compteur=0;
        for (String s : Hausse.getListe("idRuche=" + currentRucheId).split(",")){
            if (compteur++ > 0){
                this.currentHausseId = s.split(" ")[0];
                majComboCadre();
            }
            this.displayHausse.addItem(s.split(" ")[0]);
        }
        displayHausse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                displayHausseItemStateChanged(evt);
            }
        });

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Hausse courante :");

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Ruche courante :");

        jButton2.setText("Application Capteurs");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(associerRucheBouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(supprimerRuche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(displayRuches, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(associerHausseBouton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(displayHausse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addGap(12, 12, 12))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(associerRucheBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supprimerRuche, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addGap(9, 9, 9)
                .addComponent(displayRuches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(associerHausseBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayHausse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        jTabbedPane5.setBackground(new java.awt.Color(255, 255, 153));

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nomRucheAffichage.setText("Nom Ruche : " + affichage.SQLRuche("nomRuche", "idRuche=" + currentRucheId));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ruche");

        jLabel25.setText("nom :");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomRucheAffichage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomRucheAffichage, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Hausse");

        jLabel27.setText("Couleur :");

        jLabel28.setText("Numéro :");

        jLabel29.setText("Matériau :");

        textHausseCouleur.setText(" ");

        textHausseNumero.setText(" ");

        textHausseMateriau.setText(" ");

        jLabel32.setText("Température :");

        textTemperature.setText("Non mesuré");

        jLabel34.setText("Celsius");

        capteurAssociéText.setText("Capteur associé : ");

        capteurTemperatureAssocieCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionnez une hausse" }));

        associerCapteurTemperatureBouton.setText("Associer");
        associerCapteurTemperatureBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                associerCapteurTemperatureBoutonMouseClicked(evt);
            }
        });

        dissocierCapteurTemperatureBouton.setText("Dissocier");
        dissocierCapteurTemperatureBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dissocierCapteurTemperatureBoutonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(textHausseCouleur))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textHausseMateriau)
                                    .addComponent(textHausseNumero)))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(textTemperature)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel34))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(capteurAssociéText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(capteurTemperatureAssocieCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(associerCapteurTemperatureBouton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dissocierCapteurTemperatureBouton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(textHausseCouleur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(textHausseNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(textHausseMateriau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(textTemperature)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capteurTemperatureAssocieCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capteurAssociéText)
                    .addComponent(associerCapteurTemperatureBouton)
                    .addComponent(dissocierCapteurTemperatureBouton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Informations", jPanel4);

        jLabel7.setText("Reine");
        jLabel7.setFocusable(false);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setText("Couleur :");

        jLabel9.setText("Race      :");

        jLabel10.setText("Âge        :");

        jLabel11.setText("Température :");

        textCouleurAfficher.setText(affichage.SQLRuche("couleurReine", "idRuche=" + currentRucheId));

        textRaceAfficher.setText(affichage.SQLRuche("raceReine", "idRuche=" + currentRucheId));

        textAgeAfficher.setText(affichage.SQLRuche("ageReine", "idRuche=" + currentRucheId));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textCouleurAfficher, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAgeAfficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textRaceAfficher, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textCouleurAfficher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textRaceAfficher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textAgeAfficher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Essaim", jPanel5);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Intervention");

        actionEnregistrerBouton.setBackground(new java.awt.Color(255, 255, 153));
        actionEnregistrerBouton.setText("Enregistrer");
        actionEnregistrerBouton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        actionEnregistrerBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        actionEnregistrerBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionEnregistrerBoutonMouseClicked(evt);
            }
        });

        typeIntervention.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionnez une action", "Récolte d'une hausse", "Pose d'une nouvelle hausse de récolte", "Mise à jour des informations d'état et de contenu des cadres", "Extraction d'un cadre d'une hausse", "Insertion d'un cadre dans une hausse" }));
        typeIntervention.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeInterventionItemStateChanged(evt);
            }
        });

        jLabel3.setText("Type d'intervention");

        detailsText.setText("Détails");

        detailCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        detailCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                detailComboItemStateChanged(evt);
            }
        });

        panelDeuxième.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        deuxièmeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deuxièmeText.setText("/!\\ Deuxième intervention pour conserver l'intégrité /!\\");
            deuxièmeText.setOpaque(true);

            jLabel4.setText("Type d'intervention");

            detailsText1.setText("Détails");

            detailCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));

            deuxiemeIntervention.setText("     ");

            javax.swing.GroupLayout panelDeuxièmeLayout = new javax.swing.GroupLayout(panelDeuxième);
            panelDeuxième.setLayout(panelDeuxièmeLayout);
            panelDeuxièmeLayout.setHorizontalGroup(
                panelDeuxièmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDeuxièmeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelDeuxièmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deuxièmeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeuxièmeLayout.createSequentialGroup()
                            .addGroup(panelDeuxièmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelDeuxièmeLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(detailsText1)
                                    .addGap(78, 78, 78))
                                .addGroup(panelDeuxièmeLayout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(45, 45, 45)))
                            .addGroup(panelDeuxièmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(detailCombo1, 0, 280, Short.MAX_VALUE)
                                .addComponent(deuxiemeIntervention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(interventionDeux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            panelDeuxièmeLayout.setVerticalGroup(
                panelDeuxièmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDeuxièmeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(deuxièmeText)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                    .addGroup(panelDeuxièmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(interventionDeux)
                        .addComponent(deuxiemeIntervention))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelDeuxièmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(detailCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(detailsText1))
                    .addGap(20, 20, 20))
            );

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actionEnregistrerBouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(detailsText)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(detailCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(typeIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(99, 99, 99))
                        .addComponent(panelDeuxième, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(typeIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(detailCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(detailsText))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelDeuxième, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(actionEnregistrerBouton)
                    .addContainerGap())
            );

            jTabbedPane5.addTab("Actions", jPanel3);

            ajouterCadresBouton.setBackground(new java.awt.Color(255, 255, 153));
            ajouterCadresBouton.setText("Créer");
            ajouterCadresBouton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    ajouterCadresBoutonMouseClicked(evt);
                }
            });
            ajouterCadresBouton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ajouterCadresBoutonActionPerformed(evt);
                }
            });

            displayCadre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Séléctionnez une hausse" }));
            displayCadre.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    displayCadreItemStateChanged(evt);
                }
            });

            jSeparator3.setBackground(new java.awt.Color(232, 231, 231));
            jSeparator3.setForeground(new java.awt.Color(54, 46, 46));

            jLabel12.setText("Matière :");

            jLabel13.setText("État       :");

            jLabel14.setText("Contenu :");

            matiereCadre.setText("Non mesuré");

            EtatCadre.setText("Non mesuré");

            contenuCadre.setText("Non mesuré");

            jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            jLabel15.setText("Poids     :");

            poidsCadre.setText("Non mesuré");

            capteurPoisdAssociéBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionnez un cadre" }));

            textCaptPoidsAssocier.setText("Capteur associé : ");

            jLabel16.setText("kg");

            associerCapteurPoidsBouton.setText("Associer");
            associerCapteurPoidsBouton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    associerCapteurPoidsBoutonMouseClicked(evt);
                }
            });

            dissocierCapteurPoidsBouton.setText("Dissocier");
            dissocierCapteurPoidsBouton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    dissocierCapteurPoidsBoutonMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
            jPanel8.setLayout(jPanel8Layout);
            jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(textCaptPoidsAssocier)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(capteurPoisdAssociéBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(associerCapteurPoidsBouton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dissocierCapteurPoidsBouton))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(18, 18, 18)
                            .addComponent(poidsCadre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel16)))
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(poidsCadre)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(associerCapteurPoidsBouton)
                            .addComponent(dissocierCapteurPoidsBouton))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capteurPoisdAssociéBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCaptPoidsAssocier)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayCadre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ajouterCadresBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(matiereCadre))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EtatCadre)
                                        .addComponent(contenuCadre))))
                            .addGap(0, 356, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(displayCadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ajouterCadresBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(matiereCadre))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(EtatCadre))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(contenuCadre))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE))
            );

            jTabbedPane5.addTab("Cadres", jPanel6);

            jLabel21.setText("Ajouter un matériel : pas forcément dans l'application finale");

            jPanel9.setBorder(new javax.swing.border.MatteBorder(null));

            jLabel19.setText("Type");

            typeMaterielCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionnez un type", "Hausse", "Toit", "Couvercle", "Plancher", "Capteur de Poids", "Capteur de Température"}));
            typeMaterielCombo.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    typeMaterielComboItemStateChanged(evt);
                }
            });

            jLabel20.setText("Matériau");

            typeMateriauCombo.setModel(new javax.swing.DefaultComboBoxModel<Materiau>(new Materiau[] { Materiau.BOIS, Materiau.METAL, Materiau.PLASTIQUE, Materiau.POLYSTYRENE, Materiau.CRISTAL_DE_BISMUTH }));

            ajoutMateriauBouton.setBackground(new java.awt.Color(255, 255, 204));
            ajoutMateriauBouton.setText("Ajouter");
            ajoutMateriauBouton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    ajoutMateriauBoutonMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
            jPanel9.setLayout(jPanel9Layout);
            jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ajoutMateriauBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(396, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typeMateriauCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(typeMaterielCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap()))
            );
            jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(typeMateriauCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ajoutMateriauBouton)
                    .addContainerGap())
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeMaterielCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addContainerGap(54, Short.MAX_VALUE)))
            );

            jPanel10.setBorder(new javax.swing.border.MatteBorder(null));

            jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel22.setText("En stock");

            String[] listMateriels = affichage.SQLMateriau("idMateriel").split(" ");
            stockCombo.setModel(new javax.swing.DefaultComboBoxModel<>(listMateriels));

            ButtonSupprimerMateriel.setBackground(new java.awt.Color(255, 255, 204));
            ButtonSupprimerMateriel.setText("Supprimer");
            ButtonSupprimerMateriel.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    ButtonSupprimerMaterielMouseClicked(evt);
                }
            });

            jLabel17.setText("Type");

            jLabel18.setText("Matériau");

            jLabel23.setText("Contenu");

            jLabel24.setText("État");

            javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
            jPanel10.setLayout(jPanel10Layout);
            jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonSupprimerMateriel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stockCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel23)
                        .addComponent(jLabel24))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel17))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(stockCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ButtonSupprimerMateriel))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24)))
                    .addContainerGap(15, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
            jPanel7.setLayout(jPanel7Layout);
            jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel21)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            jTabbedPane5.addTab("Stock", jPanel7);

            jSplitPane1.setRightComponent(jTabbedPane5);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSplitPane1)
                    .addGap(31, 31, 31))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void associerRucheBoutonMouseClicked(java.awt.event.MouseEvent evt) {
        contI.creerNouvelleRuche();
        //displayRuches.getModel().setSelectedItem(affichage.SQLRuche("idRuche", "idRuche="+currentRucheId).split(" "));
    }

    private void displayRuchesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_displayRuchesItemStateChanged
        // TODO add your handling code here:
        this.currentRucheId = this.displayRuches.getSelectedItem().toString();
        String[] textToSet = contI.afficheSQLRuche(currentRucheId);
        this.nomRucheAffichage.setText(textToSet[4]);
        this.textCouleurAfficher.setText(textToSet[0]);
        this.textRaceAfficher.setText(textToSet[1]);
        this.textAgeAfficher.setText(textToSet[2]);
        majComboHausse();
    }//GEN-LAST:event_displayRuchesItemStateChanged

    /**
     * Affiche les Hausses associée à la ruche rentrée
     */
    public void majComboHausse(){
        this.displayHausse.removeAllItems();
        int compteur = 0;
        for (String s : Hausse.getListe("idRuche=" + currentRucheId).split(",")){
            if (compteur++ > 0){
                this.currentHausseId = s.split(" ")[0];
                majComboCadre();
            }
            this.displayHausse.addItem(s.split(" ")[0]);
        }
    }

    public void majComboCadre(){
        this.displayCadre.removeAllItems();
        int compteur = 0;
        for (String s : Cadre.getListe("idMaterielHausse = " + currentHausseId).split(",")){
            if (compteur++ > 0){
                this.currentCadreId = s.split(" ")[0];
            }
            this.displayCadre.addItem(s.split(" ")[0]);
        }
        String[] textToSet = contI.afficheSQLHausse(currentRucheId, currentHausseId);
        this.textHausseCouleur.setText(textToSet[0]);
        this.textHausseMateriau.setText(textToSet[2]);
        this.textHausseNumero.setText(textToSet[1]);
    }

    private void associerRucheBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associerRucheBoutonActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_associerRucheBoutonActionPerformed

    private void supprimerRucheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerRucheMouseClicked
        // Destruction de la ruche
        contI.supprimerRuche(currentRucheId);
    }//GEN-LAST:event_supprimerRucheMouseClicked

    private void displayRuchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayRuchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayRuchesActionPerformed

    private void ButtonSupprimerMaterielMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSupprimerMaterielMouseClicked
        // Supprimer matériaux
        int currentMaterielID = Integer.parseInt((String) this.stockCombo.getSelectedItem());
        contI.supprimerMateriel(currentMaterielID);
    }//GEN-LAST:event_ButtonSupprimerMaterielMouseClicked

    private void associerHausseBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_associerHausseBoutonMouseClicked
        contI.associerNouvelleHausse();
        this.majComboHausse();
    }//GEN-LAST:event_associerHausseBoutonMouseClicked

    private void displayHausseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_displayHausseItemStateChanged

        if (this.displayHausse.getItemCount() > 1 ){
            this.currentHausseId = this.displayHausse.getSelectedItem().toString();
            majComboCadre();
            this.contI.majCapteurTemperature(this.capteurAssociéText,
                    this.capteurTemperatureAssocieCombo,
                    this.associerCapteurTemperatureBouton,
                    this.dissocierCapteurTemperatureBouton,
                    this.currentHausseId,
                    this.textTemperature);
        }
    }//GEN-LAST:event_displayHausseItemStateChanged

    private void displayCadreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_displayCadreItemStateChanged
        if (this.displayCadre.getItemCount() > 1){
            this.currentCadreId = this.displayCadre.getSelectedItem().toString();
        }
        String[] textToSet = contI.afficheSQLCadre(currentCadreId);
        this.EtatCadre.setText(textToSet[0]);
        this.matiereCadre.setText(textToSet[1]);
        this.contenuCadre.setText(textToSet[2]);
        this.contI.majCapteurAssocie(this.capteurPoisdAssociéBox,
                currentCadreId,
                textCaptPoidsAssocier,
                capteurPoisdAssociéBox,
                associerCapteurPoidsBouton,
                dissocierCapteurPoidsBouton);

    }//GEN-LAST:event_displayCadreItemStateChanged


    private void ajouterCadresBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterCadresBoutonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterCadresBoutonActionPerformed

    private void ajouterCadresBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterCadresBoutonMouseClicked
        contI.creerNouveauCadre();
    }//GEN-LAST:event_ajouterCadresBoutonMouseClicked

    private void typeMaterielComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeMaterielComboItemStateChanged
        String select = this.typeMaterielCombo.getSelectedItem().toString();
        this.typeMateriauCombo.removeAllItems();
        if (!select.equals("Capteur de Poids") && !select.equals("Capteur de Température") && !select.equals("Hausse")){
            this.typeMateriauCombo.addItem(Materiau.BOIS);
            this.typeMateriauCombo.addItem(Materiau.METAL);
            this.typeMateriauCombo.addItem(Materiau.PLASTIQUE);
            this.typeMateriauCombo.addItem(Materiau.POLYSTYRENE);
        }
        if (select.equals("Hausse")){
            this.ajoutMateriauBouton.setText("Ouvrir interface");
        } else {
            this.ajoutMateriauBouton.setText("Ajouter");
        }
    }//GEN-LAST:event_typeMaterielComboItemStateChanged

    private void typeInterventionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeInterventionItemStateChanged
        // Au premier passage on retire le "Sélectionnez une action"
        if (this.typeIntervention.getItemCount() == 6){
            this.typeIntervention.removeItemAt(0);
        }
        String sel = this.typeIntervention.getSelectedItem().toString();
        String[] combo;
        this.detailCombo.removeAllItems();
        this.detailCombo.setVisible(true);
        this.actionEnregistrerBouton.setText("Enregistrer");
        switch(sel){
            case  "Récolte d'une hausse":
                this.detailsText.setText("Hausse récoltée :");
                combo = Hausse.getListe("idRuche=" + currentRucheId).split(",");
                for (String s : combo){
                    this.detailCombo.addItem(s);
                }
                if (Integer.parseInt(this.detailCombo.getSelectedItem().toString().split(" ")[3]) < 3){
                    this.panelDeuxième.setVisible(true);
                } else {
                    this.panelDeuxième.setVisible(false);
                }
                break;
            case "Pose d'une nouvelle hausse de récolte":
                this.detailsText.setText("Hausse posée :");
                this.detailCombo.setVisible(true);
                combo = Hausse.getListe("idRuche IS NULL").split(",");
                for (String s : combo){
                    this.detailCombo.addItem(s);
                }
                break;
            case "Mise à jour des informations d'état et de contenu des cadres":
                this.detailsText.setText("");
                this.detailCombo.setVisible(false);
                this.actionEnregistrerBouton.setText("Ouvrir l'éditeur");
                break;
            case "Extraction d'un cadre d'une hausse":
                // Conservation de l'intégrité
                this.deuxiemeIntervention.setText("Insertion d'un cadre dans une hausse");
                this.detailsText1.setText("Cadre ajouté :");
                combo = Cadre.getListe("idMaterielHausse is NULL").split(",");
                this.detailCombo1.removeAllItems();
                for (String s: combo){
                    this.detailCombo1.addItem(s);
                }
                // ComboBox
                this.detailsText.setText("Cadre extrait :");
                combo = Cadre.getListe("idMaterielHausse = " + currentHausseId).split(",");
                for (String s : combo){
                    this.detailCombo.addItem(s);
                }
                this.panelDeuxième.setVisible(true);
                break;
            case "Insertion d'un cadre dans une hausse":
                // Conservation de l'intégrité
                this.deuxiemeIntervention.setText("Extraction d'un cadre d'une hausse");
                this.detailsText1.setText("Cadre extrait :");
                combo = Cadre.getListe("idMaterielHausse = " + currentHausseId).split(",");
                this.detailCombo1.removeAllItems();
                for (String s: combo){
                    this.detailCombo1.addItem(s);
                }
                // ComboBox
                this.detailsText.setText("Cadre ajouté :");
                combo = Cadre.getListe("idMaterielHausse is NULL").split(",");
                for (String s: combo){
                    this.detailCombo.addItem(s);
                }
                this.panelDeuxième.setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_typeInterventionItemStateChanged

    private void actionEnregistrerBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionEnregistrerBoutonMouseClicked
        if (this.actionEnregistrerBouton.getText().equals("Enregistrer")){
            Boolean seconde = this.panelDeuxième.isVisible();
            String intervention = this.typeIntervention.getSelectedItem().toString();
            contI.registerIntervention(seconde, intervention, this.detailCombo1, this.detailCombo, this.currentRucheId, this.currentHausseId);
        } else {
            ModificateurDeCadre.main(currentHausseId);
        }
    }//GEN-LAST:event_actionEnregistrerBoutonMouseClicked

    private void detailComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_detailComboItemStateChanged
        try{
            this.panelDeuxième.setVisible(false);
            if (this.detailCombo.getComponentCount() >= 1){
            switch (this.typeIntervention.getSelectedItem().toString()){
                case "Récolte d'une hausse":
                     if (Integer.parseInt(this.detailCombo.getSelectedItem().toString().split(" ")[3]) < 3){
                         this.panelDeuxième.setVisible(true);
                         this.deuxiemeIntervention.setText("Pose d'une nouvelle hausse de récolte");
                         for (String s :  Hausse.getListe("idRuche IS NULL").split(",")){
                         this.detailCombo1.addItem(s);
                    }
                } else {
                    this.panelDeuxième.setVisible(false);
                }
                break;
                case "Pose d'une nouvelle hausse de récolte":
                    int id = Integer.parseInt(this.detailCombo.getSelectedItem().toString().split(" ")[3]);
                    String[] listIDs = Hausse.getListe("idRuche =" + this.currentRucheId).split(",");
                    for (String s : listIDs){
                        System.out.println("id = " + id + ", test = " + s);
                       if (Integer.parseInt(s.split(" ")[3]) == id){
                           this.panelDeuxième.setVisible(true);
                           this.deuxiemeIntervention.setText("Récolte d'une hausse");
                           this.detailCombo1.removeAllItems();
                           this.detailCombo1.addItem(s);
                           continue;
                       } else {
                           this.panelDeuxième.setVisible(false);
                       }
                    }
                    break;
                default:
                   this.panelDeuxième.setVisible(true);
            }
            } else {
                this.detailsText.setText("Pas assez de trucs voulus !");
            }
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_detailComboItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        ApplicationCapteurs appcap = new ApplicationCapteurs();
        appcap.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * Associe le capteur selectionné à la hausse sélectionnée
     * @param evt
     */
    private void associerCapteurTemperatureBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_associerCapteurTemperatureBoutonMouseClicked
         int idCapt = Integer.parseInt(this.capteurTemperatureAssocieCombo.getSelectedItem().toString());
         this.contC.associerCapteurTemperature(idCapt, currentHausseId);
    }//GEN-LAST:event_associerCapteurTemperatureBoutonMouseClicked

    /**
     * Dissocie le capteur selectionné de sa hausse
     * @param evt
     */
    private void dissocierCapteurTemperatureBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dissocierCapteurTemperatureBoutonMouseClicked
        this.contC.dissocierCapteurTemperature(currentHausseId);
    }//GEN-LAST:event_dissocierCapteurTemperatureBoutonMouseClicked

    private void associerCapteurPoidsBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_associerCapteurPoidsBoutonMouseClicked
        int idCapt = Integer.parseInt(this.capteurPoisdAssociéBox.getSelectedItem().toString());
        this.contC.associerCapteurPoids(idCapt, currentCadreId);
    }//GEN-LAST:event_associerCapteurPoidsBoutonMouseClicked

    private void dissocierCapteurPoidsBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dissocierCapteurPoidsBoutonMouseClicked
        this.contC.dissocierCapteurPoids(currentCadreId);
    }//GEN-LAST:event_dissocierCapteurPoidsBoutonMouseClicked

    private void ajoutMateriauBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMateriauBoutonMouseClicked
        String m = (String) this.typeMaterielCombo.getSelectedItem();
        if (m.startsWith("Capteur")){
            if (m.endsWith("Poids")){
                CapteurPoids cp = new CapteurPoids();
                cp.creer();
            } else {
                CapteurTemperature ct = new CapteurTemperature();
                ct.creer();
            }
        } else {
            if (m.equals("Hausse")){
                contI.creerNouvelleHausse();
            } else {
                Materiau materiau = (Materiau) this.typeMateriauCombo.getSelectedItem();
                contI.creerNouveauMateriau(m, materiau);
            }

        }
    }//GEN-LAST:event_ajoutMateriauBoutonMouseClicked

    private void undoBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undoBoutonMouseClicked
        Connection conn = BDTable.conn;
        try {
            conn.rollback();
            System.out.println("rollback\n");
        } catch (SQLException ex) {
            Logger.getLogger(Création.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_undoBoutonMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButtonSupprimerMateriel;
    private javax.swing.JLabel EtatCadre;
    private javax.swing.JButton actionEnregistrerBouton;
    private javax.swing.JToggleButton ajoutMateriauBouton;
    private javax.swing.JButton ajouterCadresBouton;
    private javax.swing.JButton associerCapteurPoidsBouton;
    private javax.swing.JButton associerCapteurTemperatureBouton;
    private javax.swing.JButton associerHausseBouton;
    private javax.swing.JButton associerRucheBouton;
    private javax.swing.JLabel capteurAssociéText;
    private javax.swing.JComboBox<String> capteurPoisdAssociéBox;
    private javax.swing.JComboBox<String> capteurTemperatureAssocieCombo;
    private javax.swing.JLabel contenuCadre;
    private javax.swing.JComboBox<String> detailCombo;
    private javax.swing.JComboBox<String> detailCombo1;
    private javax.swing.JLabel detailsText;
    private javax.swing.JLabel detailsText1;
    private javax.swing.JLabel deuxiemeIntervention;
    private javax.swing.JLabel deuxièmeText;
    private javax.swing.JComboBox displayCadre;
    private javax.swing.JComboBox displayHausse;
    private javax.swing.JComboBox displayRuches;
    private javax.swing.JButton dissocierCapteurPoidsBouton;
    private javax.swing.JButton dissocierCapteurTemperatureBouton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel interventionDeux;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JLabel matiereCadre;
    private javax.swing.JLabel nomRucheAffichage;
    private javax.swing.JPanel panelDeuxième;
    private javax.swing.JLabel poidsCadre;
    private javax.swing.JComboBox<String> stockCombo;
    private javax.swing.JButton supprimerRuche;
    private javax.swing.JLabel textAgeAfficher;
    private javax.swing.JLabel textCaptPoidsAssocier;
    private javax.swing.JLabel textCouleurAfficher;
    private javax.swing.JLabel textHausseCouleur;
    private javax.swing.JLabel textHausseMateriau;
    private javax.swing.JLabel textHausseNumero;
    private javax.swing.JLabel textRaceAfficher;
    private javax.swing.JLabel textTemperature;
    private javax.swing.JComboBox typeIntervention;
    private javax.swing.JComboBox<Materiau> typeMateriauCombo;
    private javax.swing.JComboBox<String> typeMaterielCombo;
    private javax.swing.JButton undoBouton;
    // End of variables declaration//GEN-END:variables
}
